#!/bin/sh

### BEGIN INIT INFO
# Provides:        timeserver
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:    1
# Short-Description: Start time service
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin/:/usr/local/bin

. /lib/lsb/init-functions

DAEMON1=/usr/local/bin/wwvbtool
PIDFILE1=/var/run/wwvbtool.pid
DAEMON2=/home/pi/bin/hourglass.py
PIDFILE2=/var/run/hourglass.pid

WWVBTOOL_OPTS="-l -u -r -s -p -b"

test -x $DAEMON1 || exit 5
test -x $DAEMON2 || exit 5

case $1 in
	start)
		log_daemon_msg "Reading hardware clock" "timeservice"
		hwclock -u -s
		status=$?
		log_end_msg $status
		log_daemon_msg "Starting wwvbtool daemon" "timeservice"
		start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE1 --startas $DAEMON1 -- $WWVBTOOL_OPTS
		status=$?
		log_end_msg $status
		log_daemon_msg "Starting hourglass daemon" "timeservice"
		start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE2 --startas $DAEMON2 --make-pidfile --background --
		status=$?
		log_end_msg $status
		;;
	stop)
		log_daemon_msg "Stopping wwvbtool" "timeservice"
		start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE1
		log_end_msg $?
		log_daemon_msg "Stopping hourglass" "timeservice"
		start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE2 --remove-pidfile
		log_end_msg $?
		log_daemon_msg "Writing hardware clock" "timeservice"
		hwclock -u -w
		status=$?
		log_end_msg $status
		rm -f $PIDFILE1 $PIDFILE2
		;;
	restart|force-reload)
		$0 stop && sleep 2 && $0 start
		;;
	try-restart)
		if $0 status >/dev/null; then
			$0 restart
		else
			exit 0
		fi
		;;
	reload)
		exit 3
		;;
	status)
		status_of_proc $DAEMON1 "time service"
		status_of_proc $DAEMON2 "time service"
		;;
	*)
		echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
		exit 2
		;;
esac

# end
